### ISSUE TITLE
"Remember Me" functionality

### ISSUE THREAD

**Issue by alexanderpepper** [langateam/sails-permissions#243]
How can I make login persist after the browser is closed or the server is restarted?

**Comment by westlakem** [comment]
@alexanderpepper if you use redis or MongoDB to cache your sessions, then they will continue to remain logged in until the session expires or your browser clears cookies.  You can test it by setting up a free redis instance at RedisLabs(NOT ASSOCIATED), login, kill your server and start it back up, you should see the user is still logged in.   

You can see how at http://sailsjs.org/documentation/concepts/deployment/scaling

**Comment by alexanderpepper** [comment]
Excellent. Ended up using MongoDB. Thank you.
